### ISSUE TITLE
temporary input interface improvements

### ISSUE THREAD

**Issue by D13Lee** [Project-Rekt/rekt#6]
extend player interaction by adding pseudo buttons off to the side of the game. detect when these buttons are clicked on and invoke their action. Create a generic button class to inherit from to ease modularity.

**Comment by Squishy123** [comment]
We can probably use DOM buttons for this, it'll be more energy efficient than canvas pseudo buttons. #savetheearth

**Comment by D13Lee** [comment]
bare basics interface working, can optionally change to a better form if necessary, but it will do for now.
