### ISSUE TITLE
Status effects

### ISSUE THREAD

**Issue by D13Lee** [Project-Rekt/rekt#7]
in order to give towers more personality, they should be able to inflict a variety of status ailments to add more strategy to the game, such as a slow, poison, defense reduction, or stun effect. Perhaps there will be monsters that will be able to give buffs to their peers? These effects can be generalized to a StatusEffect object type that is attached to monsters while they are alive. This will be a generic class where practical status effects will inherit from. This does not need to inherit from Actor, as any operations should be done within the attached monster's update(dt) cycle. 

Specifically we need a generic status effect that can be
1. attached to a monster (a monster may have several status effects attached to it)
2. expire (time out according to a monster's update(dt))
3. affect the state of the monster it is attached to (with effects like slow or defense reduction these changes should be made with the function attach() where these one time changes are applied)
4. revert any changes made upon expiration (while attach() applies effects, there should be a function called expire() called when the status effect times out, where changes are reverted)

**Comment by Squishy123** [comment]
So should each monster have pre-defined functions that handle a status effect with a multiplier?
e.g.
```
attachEffect(effect) {
this.effects.push(effect)
}

//inside monster.class
handleSlow() {
    this.effects.forEach(e => {
        if(e.type == "slow") {
        this.speed *= e.quantity;
        }
    });
}
```

**Comment by D13Lee** [comment]
No, each monster class has a loop within their update(dt) that passes dt into the update(dt) of the status effect. The monster doesn't care what the status effect is or what it does, the effect will deal with any changes it makes on its own. Aside from perhaps the monster keeping track of its original stat vs its changeable stat, so we can't get things like negative speed

**Comment by D13Lee** [comment]
to go more into detail, a tower will invoke monster.addStatusEffect(effect). addStatusEffect(effect) will invoke effect.attach() to deal with any immediate effects like stat changes, while keeping track of it by putting the effect into a list called this.effects. If there are stats that makes sense to be limited; such as speed being a minimum of .01 for example, we can keep track of two speeds. A max speed that is not edited, and a mutable speed that is interacted with by status effects. Then when speed is required in movement, return the max between the mutable speed and .01

**Comment by D13Lee** [comment]
when tracking the effects of binary status effects like stun or reverse, keep track of it as an integer, where stun > 0 means monster is stunned. This way multiple status effects can do monster.stunned + 1 on attach or - 1 on dispel without interfering with each other

**Comment by OneHandKlap** [comment]
I will take this one

**Comment by OneHandKlap** [comment]
Did we have ideas for status effects other than stun/slow/defense debuff?

**Comment by D13Lee** [comment]
I do not think we discussed that at length. Because of these unknowns, perhaps it would be worth doing to move stats to being tracked as key-value pairs instead? In regards to more varieties than what you mentioned, stuns, slows only need to do something to the monster it is attached to twice over its life cycle: reduce stat on attach, and increase stat on dispel. A bleed or poison effect however, would need to act on the monster's HP once every n milliseconds. Maybe a confusion debuff would temporarily flip a monster's movement direction (this would be challenging to implement due to needing to slog through the movement module but doable). 

There can also be similar but distinct effects, like if you wanted to implement both poison and bleed, maybe poison does less DPS than bleed, but ignores defense, whereas bleed has higher DPS but is affected by armor?

You can also add more depth to effects, like stunning a monster decreases the effectiveness of any further stuns by a stacking factor of n%? perhaps this diminishing return could be implemented as a status effect as well?

**Comment by OneHandKlap** [comment]
finished. See docss
